//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using Hst.Domain.Entities;

namespace Hst.DataAccess
{
    public partial class HstDBContainer : ObjectContext
    {
        public const string ConnectionString = "name=HstDBContainer";
        public const string ContainerName = "HstDBContainer";
    
        #region Constructors
    
        public HstDBContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public HstDBContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public HstDBContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Child> Children
        {
            get { return _children  ?? (_children = CreateObjectSet<Child>("Children")); }
        }
        private ObjectSet<Child> _children;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<StateRequiredSubject> StateRequiredSubjects
        {
            get { return _stateRequiredSubjects  ?? (_stateRequiredSubjects = CreateObjectSet<StateRequiredSubject>("StateRequiredSubjects")); }
        }
        private ObjectSet<StateRequiredSubject> _stateRequiredSubjects;
    
        public ObjectSet<Subject> Subjects
        {
            get { return _subjects  ?? (_subjects = CreateObjectSet<Subject>("Subjects")); }
        }
        private ObjectSet<Subject> _subjects;
    
        public ObjectSet<Lesson> Lessons
        {
            get { return _lessons  ?? (_lessons = CreateObjectSet<Lesson>("Lessons")); }
        }
        private ObjectSet<Lesson> _lessons;
    
        public ObjectSet<Activity> Activities
        {
            get { return _activities  ?? (_activities = CreateObjectSet<Activity>("Activities")); }
        }
        private ObjectSet<Activity> _activities;
    
        public ObjectSet<Test> Tests
        {
            get { return _tests  ?? (_tests = CreateObjectSet<Test>("Tests")); }
        }
        private ObjectSet<Test> _tests;
    
        public ObjectSet<TestResult> TestResults
        {
            get { return _testResults  ?? (_testResults = CreateObjectSet<TestResult>("TestResults")); }
        }
        private ObjectSet<TestResult> _testResults;
    
        public ObjectSet<School> Schools
        {
            get { return _schools  ?? (_schools = CreateObjectSet<School>("Schools")); }
        }
        private ObjectSet<School> _schools;

        #endregion
    }
}
