//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Hst.Domain.Entities
{
    [Serializable]
    public partial class User
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Login
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual string NameFirst
        {
            get;
            set;
        }
    
        public virtual string NameLast
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsTeacher
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SchoolId
        {
            get { return _schoolId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_schoolId != value)
                    {
                        if (School != null && School.Id != value)
                        {
                            School = null;
                        }
                        _schoolId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _schoolId;

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Child> Children
        {
            get
            {
                if (_children == null)
                {
                    var newCollection = new FixupCollection<Child>();
                    newCollection.CollectionChanged += FixupChildren;
                    _children = newCollection;
                }
                return _children;
            }
            set
            {
                if (!ReferenceEquals(_children, value))
                {
                    var previousValue = _children as FixupCollection<Child>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupChildren;
                    }
                    _children = value;
                    var newValue = value as FixupCollection<Child>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupChildren;
                    }
                }
            }
        }
        private ICollection<Child> _children;
    
        public virtual ICollection<Lesson> Lessons
        {
            get
            {
                if (_lessons == null)
                {
                    var newCollection = new FixupCollection<Lesson>();
                    newCollection.CollectionChanged += FixupLessons;
                    _lessons = newCollection;
                }
                return _lessons;
            }
            set
            {
                if (!ReferenceEquals(_lessons, value))
                {
                    var previousValue = _lessons as FixupCollection<Lesson>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLessons;
                    }
                    _lessons = value;
                    var newValue = value as FixupCollection<Lesson>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLessons;
                    }
                }
            }
        }
        private ICollection<Lesson> _lessons;
    
        public virtual ICollection<Activity> Activities
        {
            get
            {
                if (_activities == null)
                {
                    var newCollection = new FixupCollection<Activity>();
                    newCollection.CollectionChanged += FixupActivities;
                    _activities = newCollection;
                }
                return _activities;
            }
            set
            {
                if (!ReferenceEquals(_activities, value))
                {
                    var previousValue = _activities as FixupCollection<Activity>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupActivities;
                    }
                    _activities = value;
                    var newValue = value as FixupCollection<Activity>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupActivities;
                    }
                }
            }
        }
        private ICollection<Activity> _activities;
    
        public virtual ICollection<Test> Tests
        {
            get
            {
                if (_tests == null)
                {
                    var newCollection = new FixupCollection<Test>();
                    newCollection.CollectionChanged += FixupTests;
                    _tests = newCollection;
                }
                return _tests;
            }
            set
            {
                if (!ReferenceEquals(_tests, value))
                {
                    var previousValue = _tests as FixupCollection<Test>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTests;
                    }
                    _tests = value;
                    var newValue = value as FixupCollection<Test>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTests;
                    }
                }
            }
        }
        private ICollection<Test> _tests;
    
        public virtual School School
        {
            get { return _school; }
            set
            {
                if (!ReferenceEquals(_school, value))
                {
                    var previousValue = _school;
                    _school = value;
                    FixupSchool(previousValue);
                }
            }
        }
        private School _school;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupSchool(School previousValue)
        {
            if (previousValue != null && previousValue.Users.Contains(this))
            {
                previousValue.Users.Remove(this);
            }
    
            if (School != null)
            {
                if (!School.Users.Contains(this))
                {
                    School.Users.Add(this);
                }
                if (SchoolId != School.Id)
                {
                    SchoolId = School.Id;
                }
            }
            else if (!_settingFK)
            {
                SchoolId = null;
            }
        }
    
        private void FixupChildren(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Child item in e.NewItems)
                {
                    if (!item.Users.Contains(this))
                    {
                        item.Users.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Child item in e.OldItems)
                {
                    if (item.Users.Contains(this))
                    {
                        item.Users.Remove(this);
                    }
                }
            }
        }
    
        private void FixupLessons(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Lesson item in e.NewItems)
                {
                    if (!item.Users.Contains(this))
                    {
                        item.Users.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Lesson item in e.OldItems)
                {
                    if (item.Users.Contains(this))
                    {
                        item.Users.Remove(this);
                    }
                }
            }
        }
    
        private void FixupActivities(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Activity item in e.NewItems)
                {
                    if (!item.Users.Contains(this))
                    {
                        item.Users.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Activity item in e.OldItems)
                {
                    if (item.Users.Contains(this))
                    {
                        item.Users.Remove(this);
                    }
                }
            }
        }
    
        private void FixupTests(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Test item in e.NewItems)
                {
                    if (!item.Users.Contains(this))
                    {
                        item.Users.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Test item in e.OldItems)
                {
                    if (item.Users.Contains(this))
                    {
                        item.Users.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
